---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Schlafen
- type: directory
  path: content/wohnungen
  label: Wohnungen
  create: all
  match: "**/*"
  templates:
  - apartment
- type: directory
  path: content/zimmer
  label: Zimmer
  create: all
  match: "**/*"
  templates:
  - room
- type: heading
  label: Feiern
- type: heading
  label: Essen
- type: directory
  path: content/gastronomie
  label: Gastronomie
  create: all
  match: "**/*"
  templates:
  - gastronomy
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
