---
label: Default
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: Titel
- name: title_emotional
  type: text
  config:
    required: false
  label: Emotionaler Titel
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Text
- name: cover
  type: file
  config:
    maxSize: 64
  label: Cover
- name: references
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: pages
      section: ''
  label: Referenzen
pages:
- content/essen.md
- content/schlafen.md
