---
label: Default
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Titel
- name: title_emotional
  type: text
  config:
    required: false
  label: Emotionaler Titel
- name: cover
  type: file
  config:
    maxSize: 64
  label: Cover
- name: meta
  type: include
  config: {}
  template: meta
  label: Meta
pages:
- content/essen.md
- content/feiern.md
- content/schlafen.md
